export const styles = {
  page: {
    width: "100vw",            
    minHeight: "100vh",
    backgroundColor: "#f1f5f9",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    display: "flex",         
    flexDirection: "column",   
    margin: 0,
    padding: 0,
    boxSizing: "border-box",
  },
  containerCenter: {
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  navbar: {
    width: "100%",              
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 10%",          
    height: "75px",
    backgroundColor: "#fff",
    borderBottom: "1px solid #e2e8f0",
    boxSizing: "border-box",
  },
  logo: {
    fontSize: "22px",
    fontWeight: "800",
    color: "#0f172a",
  },
  logoutBtn: {
    padding: "8px 20px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    cursor: "pointer",
    background: "#fff",
    fontWeight: "600",
    color: "#64748b",
  },
  content: {
    width: "100%",
    maxWidth: "1000px",        
    margin: "40px auto",       
    padding: "0 20px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "32px",
  },
  header: {
    marginBottom: "30px",
  },
  title: {
    fontSize: "30px",
    fontWeight: "700",
    color: "#1e293b",
    margin: 0,
  },
  subtitle: {
    color: "#64748b",
    fontSize: "15px",
    marginTop: "5px",
  },
  balanceCard: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#2563eb", 
    padding: "35px",
    borderRadius: "16px",
    marginBottom: "0px",
    boxShadow: "0 10px 20px -5px rgba(37, 99, 235, 0.4)", 
    boxSizing: "border-box",
    width: "100%",
  },
  cardLabel: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.8)", 
    textTransform: "uppercase",
    letterSpacing: "1px",
    fontWeight: "600",
  },
  balanceValue: {
    fontSize: "40px",
    fontWeight: "700",
    color: "#ffffff",
    margin: "8px 0",
  },
  actionsContainer: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.2)", 
    padding: "8px 16px",
    borderRadius: "20px",
    fontSize: "13px",
    fontWeight: "600",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    backgroundColor: "#4ade80", 
    borderRadius: "50%",
  },
  transactionsCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: "20px",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.05)",
    boxSizing: "border-box",
  },
  cardTitle: {
    padding: "25px",
    fontSize: "19px",
    fontWeight: "700",
    borderBottom: "1px solid #f1f5f9",
    margin: 0,
    color: "#334155",
  },
  list: {
    display: "flex",
    flexDirection: "column",
  },
  listItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "20px 25px",
    borderBottom: "1px solid #f8fafc",
  },
  itemInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  itemType: {
    fontWeight: "800",
    fontSize: "13px",
    textTransform: "uppercase",
    color: "#475569",
  },
  itemDesc: {
    fontSize: "14px",
    color: "#64748b",
  },
  itemDate: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  itemValues: {
    textAlign: "right",
  },
  itemAmount: {
    fontWeight: "800",
    fontSize: "17px",
  },
  balanceAfter: {
    fontSize: "12px",
    color: "#94a3b8",
    display: "block",
    marginTop: "6px",
  },
  emptyMsg: {
    padding: "50px",
    textAlign: "center",
    color: "#94a3b8",
  },
  depositBtn: {
    backgroundColor: "#ffffff",
    color: "#2563eb",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontWeight: "700",
    cursor: "pointer",
    fontSize: "15px",
    width: "fit-content",
    alignSelf: "center",
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
    transition: "0.2s"
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: "20px",
    boxSizing: "border-box",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: "32px",
    borderRadius: "16px",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
  },
  modalTitle: {
    margin: "0 0 8px 0",
    fontSize: "20px",
    color: "#1e293b",
  },
  modalSubtitle: {
    fontSize: "14px",
    color: "#64748b",
    marginBottom: "24px",
  },
  inputHelp: {
    fontSize: "11px",
    color: "#94a3b8",
    marginTop: "4px",
  },
  modalActions: {
    display: "flex",
    gap: "12px",
    marginTop: "24px",
  },
  cancelBtn: {
    flex: 1,
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    backgroundColor: "#fff",
    color: "#64748b",
    fontWeight: "600",
    cursor: "pointer",
  },
  confirmBtn: {
    flex: 2,
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#2563eb",
    color: "#fff",
    fontWeight: "600",
    cursor: "pointer",
  },
  modalContentWide: {
      backgroundColor: "#ffffff",
      padding: "32px",
      borderRadius: "20px",
      width: "95%",
      maxWidth: "1000px",
      maxHeight: "85vh",
      display: "flex",
      flexDirection: "column",
      boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      boxSizing: "border-box",
    },
    modalHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "24px",
    },
    closeModalBtn: {
      background: "none",
      border: "none",
      fontSize: "20px",
      color: "#64748b",
      cursor: "pointer",
      padding: "8px",
    },
    filterSection: {
      display: "flex",
      gap: "16px",
      padding: "16px",
      backgroundColor: "#f8fafc",
      borderRadius: "12px",
      marginBottom: "20px",
      alignItems: "center",
      flexWrap: "wrap",
    },
    scrollArea: {
      overflowY: "auto",
      flex: 1,
      paddingRight: "8px",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      textAlign: "left",
    },
    th: {
      padding: "12px 16px",
      fontSize: "13px",
      color: "#64748b",
      textTransform: "uppercase",
      letterSpacing: "0.5px",
      borderBottom: "2px solid #f1f5f9",
      fontWeight: "600",
    },
    td: {
      padding: "16px",
      fontSize: "14px",
      color: "#1e293b",
    },
    tdType: {
      padding: "16px",
      fontSize: "12px",
      fontWeight: "800",
      textTransform: "uppercase",
      color: "#475569",
    },
    tdDesc: {
      padding: "16px",
      fontSize: "14px",
      color: "#64748b",
      maxWidth: "250px",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    tdValue: {
      padding: "16px",
      fontSize: "15px",
      fontWeight: "700",
      textAlign: "right",
    },
    tdSaldo: {
      padding: "16px",
      fontSize: "14px",
      color: "#94a3b8",
      textAlign: "right",
      fontWeight: "500",
    },
    inputGroupSmall: {
      display: "flex",
      flexDirection: "column",
      gap: "4px",
    },
    labelSmall: {
      fontSize: "11px",
      fontWeight: "700",
      color: "#94a3b8",
      textTransform: "uppercase",
    },
    inputSmall: {
      padding: "8px 12px",
      borderRadius: "6px",
      border: "1px solid #e2e8f0",
      fontSize: "13px",
      color: "#1e293b",
      outline: "none",
      backgroundColor: "#fff",
    },
    clearFiltersBtn: {
      alignSelf: "flex-end",
      padding: "10px 15px",
      fontSize: "12px",
      fontWeight: "600",
      color: "#ef4444",
      background: "none",
      border: "1px solid #fee2e2",
      borderRadius: "6px",
      cursor: "pointer",
      transition: "0.2s",
    },
    "@keyframes fadeIn": {
      "0%": { opacity: 0, transform: "translateY(5px)" },
      "100%": { opacity: 1, transform: "translateY(0)" }
    },
    tableRow: {
      borderBottom: "1px solid #f1f5f9",
      transition: "background-color 0.2s ease", 
      animation: "fadeIn 0.3s ease-out forwards", 
    },
    badge: {
      padding: "4px 10px",
      borderRadius: "12px",
      fontSize: "11px",
      fontWeight: "700",
      textTransform: "uppercase",
      display: "inline-block",
      whiteSpace: "nowrap",
    },
    adminSection: {
      backgroundColor: "#1e293b", 
      padding: "20px 30px",
      borderRadius: "12px",
      marginBottom: "24px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    },
    adminBadge: {
      backgroundColor: "#6366f1", 
      color: "#fff",
      padding: "4px 8px",
      borderRadius: "4px",
      fontSize: "16px",
      fontWeight: "bold",
      textTransform: "uppercase",
    },
    adminBtn: {
      backgroundColor: "#fff",
      color: "#1e293b",
      border: "none",
      padding: "10px 20px",
      borderRadius: "8px",
      fontWeight: "700",
      cursor: "pointer",
      fontSize: "13px",
    },
    adminActionBtn: {
      backgroundColor: "#f1f5f9",
      color: "#475569",
      border: "1px solid #e2e8f0",
      padding: "6px 12px",
      borderRadius: "6px",
      fontSize: "12px",
      fontWeight: "600",
      cursor: "pointer",
      transition: "0.2s",
    },
};